spring:
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.sql: trace
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.orm.extract: trace





